[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.2.2"
[build]
  command = ""          # don't run Jekyll or anything
  publish = "_site"     # deploy the already-prepared files

